language: java

addons:
    # sonarcloud:
        # organization: "abcdabcd"
        # token: $SONAR_TOKEN
        # branch: "master"

script:
    - ant compile
    - sonar-scanner -X -Dsonar.login=$SONAR_TOKEN