language: java

addons:
    sonarcloud:
        organization: "abcdabcd"
        token: 
            secure: $SONAR_TOKEN
        branch: "master"

script:
    - ant compile
    - sonar-scanner -X
    